### ISSUE TITLE
Cannot Renew - 651 char:3 "Unexpected status Value"

### ISSUE THREAD

**Issue by conroyke56** [dansmith65/FileMaker-LetsEncrypt-Win#8]
Come around to renewing my certificate.
Schedule failed.
When i try to renew manually, i get the attached error.

Cant figure out if its a bug or something i am missing. 

Using: Set-ExecutionPolicy Bypass -Scope Process - Force;
-renew.

![RENEW SSL FILEMAKER](https://user-images.githubusercontent.com/33205454/74792807-986cb800-5312-11ea-81c0-d4702e78f850.PNG)

**Comment by dansmith65** [comment]
I'm not quite sure what  happened there. I think an earlier version of the script may have not expected the *pending* status, which is rarely returned.

I would recommending switching to the code from the dev branch. It's gone through a major rewrite to use an ACMEv2 client, since the [v1 client is being disabled](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430) . Here's a comment on another issue showing how to get started with the dev code: https://github.com/dansmith65/FileMaker-LetsEncrypt-Win/issues/5#issuecomment-558002772

**Comment by conroyke56** [comment]
Thanks for the reply. 

Yeh. This is the latest dev code. Downloaded it today.

I used it 3 months ago and help you test it. Had no problems. 

Maybe someone else can try to renew. See if they come across the same issue.

**Comment by dansmith65** [comment]
In that case, you might just want to try again. I do remember having an intermittent issue with the status. I thought I fixed it, but I guess not. If that doesn't work and you really need to get it renewed, you can likely manually go through the same steps that the script does. You should be able to start where the script failed, so you don't have to do the entire thing.

**Comment by conroyke56** [comment]
yeh, tried a few times. still the same issue :(

**Comment by dansmith65** [comment]
Did you download the latest changes? I assumed I fixed it and even updated my server's certificate recently.

**Comment by conroyke56** [comment]
yeh, after your did the next push, a timer came up, and task was completed within the timer, but still go the same error. 651 char3 unexpected status value.

then today loaded the latest dev branch, and the script wouldn't
![dev images](https://user-images.githubusercontent.com/33205454/75399751-38e55c80-5951-11ea-9e43-71ad9f512fd0.PNG)
 even start.

TRying to go through the code to see what might be causing the issue. but cant work it out :(

**Comment by conroyke56** [comment]
if you'd like, i am happy to share my screen with you, so you can look a little closer.

**Comment by dansmith65** [comment]
I made a few changes after I updated my certificate; It looks like one of those changes broke something and I didn't test it afterwards. I just pushed another commit to dev branch. Try downloading and running again; I'm hoping it will work this time.

**Comment by conroyke56** [comment]
you gonna  hate me haha.
661 Char:3

Guessing its the same error, but just a little lower cause you've
 added a few extra lines of code?

![CaptureA](https://user-images.githubusercontent.com/33205454/75405029-82897380-5960-11ea-8cce-517b6aa17fdd.PNG)

**Comment by dansmith65** [comment]
This doesn't look like an error in the script. The order is "invalid"; I've never gotten that state myself, but I think you might be able to fix it by starting over with:

    .\GetSSL.ps1 -Setup -Domains fms.example.com, fms.example2.com -Emails user@email.com, user2@email.com -Force

Note that you might need the `-Force` parameter to get it to overwrite the current invalid order. If this still doesn't work, you might need to directly call Posh-ACME commands to clean up your environment and get a fresh start. Some info on that is here: https://github.com/rmbolger/Posh-ACME/wiki/(Advanced)-Manual-HTTP-Challenge-Validation. You would basically be viewing and maybe deleting orders and authorizations. As far as I know, this _shouldn't_ be necessary though, as my script should be able to overwrite everything.

If you still have issues, please send the full log file (maybe review it for sensitive info; I'm not sure if anything sensitive is added to it or not). You can email it to me instead of posting here.

P.S. I'm glad to see you're using Staging server while testing this!

**Comment by conroyke56** [comment]
dumb me had closed port 80 for some unknown reason. re-opened problem solved. staging worked perfectly, but without staging it didn't.
Again, might be simple. ill close this issue, and post a new one with that.

Thanks,
